print("R_LIBS_USER ---")
Sys.getenv(R_LIBS_USER)
Sys.setenv(R_LIBS_USER="/root/.cache/R/renv/library/project-2adda8ef/R-4.1/x86_64-pc-linux-gnu:/usr/local/lib/R/library")
print("R_LIBS_USER ---")
Sys.getenv(R_LIBS_USER)
print(".libPaths() ---")
print(.libPaths())
# print(getwd())
print(as.data.frame(installed.packages()[,c(1,3)]))
print(Sys.getenv())
print(Sys.getenv("RENV_PATHS_CACHE"))

options(shiny.port = as.numeric(Sys.getenv("PORT")), shiny.host='0.0.0.0', shiny.fullstacktrace = TRUE)
golem.test::run_app()
