name: Release to GCR (v1)

on:
  push:
    branches: ["staging"]

env:
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: "0.0.0.9000"
  PROJECT_ID: dbt-def-project-001
  SA: gh-runner

jobs:
  deploy:
    runs-on: ubuntu-latest #run this workflow on ubuntu instance
    permissions: #make sure we add permission to read and write package
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1 #checkouts your repo, so this workflow can access it

#      - name: Authenticate to GCP (DEPRECATED)
#        env:
#          PROJECT_ID: dbt-def-project-001 #create env called PROJECT_ID consisted of our actual GCP Project ID
#        #uses: google-github-actions/setup-gcloud@v0.3.0 #checkouts GCR repo, so this workflow can access it
#        uses: google-github-actions/setup-gcloud@main #checkouts GCR repo, so this workflow can access it
#        with:
#          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }} #parse the value of repository secret called SERVICE_ACCOUNT_KEY that we have created earlier
#          project_id: ${{ env.PROJECT_ID }} #parse the value of env called PROJECT_ID
#          export_default_credentials: true

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v0
        with:
          create_credentials_file: 'true'
          workload_identity_provider: 'projects/558965742626/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: '{{ env.SA }}@dbt-def-project-001.iam.gserviceaccount.com'

      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Configure Docker Client
        run:  |-
          gcloud auth configure-docker --quiet #authenticate to gcr
          gcloud auth login

      - name: Push Docker Image to Container Registry GCR
        run: |-
          docker tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} eu.gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker push eu.gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
